"""PDF case report export."""

from __future__ import annotations

from io import BytesIO
from typing import Any

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer


def build_case_pdf(
    case: dict[str, Any],
    *,
    timeline: list[dict[str, Any]] | None = None,
    events: list[dict[str, Any]] | None = None,
) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm)
    styles = getSampleStyleSheet()
    story: list = []

    story.append(Paragraph("Alkhidmat Relief Copilot — Case Report", styles["Title"]))
    story.append(Spacer(1, 8))
    story.append(
        Paragraph(
            f"<b>Ticket:</b> {case.get('ticket_id') or '—'} &nbsp; "
            f"<b>Status:</b> {case.get('status')} &nbsp; "
            f"<b>Case ID:</b> {case.get('id')}",
            styles["Normal"],
        )
    )
    story.append(Spacer(1, 6))
    story.append(Paragraph("<b>Request</b>", styles["Heading2"]))
    story.append(Paragraph((case.get("raw_message") or "").replace("\n", "<br/>"), styles["Normal"]))
    story.append(Spacer(1, 6))

    story.append(Paragraph("<b>Classification</b>", styles["Heading2"]))
    story.append(
        Paragraph(
            f"Category: {case.get('category')} | Priority: {case.get('priority')} | "
            f"Language: {case.get('language')}<br/>"
            f"Location: {case.get('location')}<br/>"
            f"Requester: {case.get('requester_name')} / {case.get('requester_phone')}<br/>"
            f"Risk: {case.get('risk_score')} | Duplicate: {case.get('duplicate_flag')}",
            styles["Normal"],
        )
    )

    if case.get("hitl_decision"):
        story.append(Spacer(1, 6))
        story.append(Paragraph("<b>Supervisor</b>", styles["Heading2"]))
        story.append(
            Paragraph(
                f"Decision: {case.get('hitl_decision')}<br/>Note: {case.get('hitl_note') or '—'}",
                styles["Normal"],
            )
        )

    hits = case.get("sop_hits") or []
    if hits:
        story.append(Spacer(1, 6))
        story.append(Paragraph("<b>SOP citations</b>", styles["Heading2"]))
        for hit in hits:
            story.append(
                Paragraph(
                    f"• <b>{hit.get('title')}</b> ({hit.get('category')}) — {hit.get('excerpt', '')[:200]}",
                    styles["Normal"],
                )
            )

    stages = timeline or []
    if stages:
        story.append(Spacer(1, 6))
        story.append(Paragraph("<b>Timeline</b>", styles["Heading2"]))
        for stage in stages:
            if stage.get("state") == "skipped":
                continue
            story.append(
                Paragraph(
                    f"• [{stage.get('state')}] {stage.get('label')}: {stage.get('detail') or ''}",
                    styles["Normal"],
                )
            )

    if events:
        story.append(Spacer(1, 6))
        story.append(Paragraph("<b>Audit events</b>", styles["Heading2"]))
        for event in events[-12:]:
            story.append(
                Paragraph(
                    f"• {event.get('created_at')} — {event.get('actor')} / {event.get('event_type')}: "
                    f"{event.get('detail') or ''}",
                    styles["Normal"],
                )
            )

    story.append(Spacer(1, 12))
    story.append(
        Paragraph(
            "<i>Generated by Alkhidmat Relief Copilot — Multi-Agent Aid Desk (Alibaba Cloud AI Hackathon Pakistan 2026).</i>",
            styles["Normal"],
        )
    )
    doc.build(story)
    return buffer.getvalue()
